AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Sample Template for Investor Portal

Parameters:
  TargetEnvr:
    Type: String
    Default: dev
    Description: "The target environment"

  VPCId:
    Type: String
    Default: "vpc-091e94554a3b4699e"  #Replace with newly Created VPC ID
  
  AvailabilityZoneA:
    Type: String
    Default: "eu-west-1a"
  
  NatGateWayName: #Update the NAT Gatway Name as your VPC
    Type: String
    Default: "nat-093e9533acf277f22"
  
  InstanceTypeParameterBackendVM: #BackendVM    
    Description: Select instance Type
    Type: String
    Default: t2.large

  DefaultSecuirtyGroupName:
    Type: String
    Default: "sg-09214fa70a6709eb6" #Update the SG Name as per your VPC

  BackEndVMSubnetId:
    Description: "Bastian VM is in Private Subnet A"
    Type: String
    Default: "subnet-07e04600d6fa9c4f9" #Check in which subnet you want to run your instance PVT or PUB change the name

  KeyValuePair:
    Type: String
    Default: "In-dev-keypair" 

Resources:  
  # Creating Security Group
  BESecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: My Global Security Group
        VpcId: !Ref VPCId
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '22'
            ToPort: '22'
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: '80'
            ToPort: '80'
            CidrIp: 0.0.0.0/0
        SecurityGroupEgress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
    # Volume for Jenkins. 
  BackendVolume:
    Type: AWS::EC2::Volume
    Properties: 
      Size: 50
      Encrypted: true
      AvailabilityZone: !Ref AvailabilityZoneA
      Tags:
        - Key: "Name"
          Value: in-prepro-volume-Backend
    #DeletionPolicy: snapshot
  
  BackendMountPoint:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      InstanceId: !Ref BackEndInstance
      VolumeId: !Ref BackendVolume
      Device: /dev/sdh
  
  BackEndInstance:  #Make sure to change the Image ID incase of different Region.
    Type: AWS::EC2::Instance
    #DeletionPolicy: Retain
    Properties:
      InstanceType: !Ref InstanceTypeParameterBackendVM
      ImageId: ami-0d71ea30463e0ff8d
      KeyName: !Ref KeyValuePair
      IamInstanceProfile: INBackend
      #IamInstanceProfile: EC2Deployer
      Tags:
        - Key: "Name"
          Value: in-dev-backendvm
      NetworkInterfaces:
      - GroupSet: 
        - !Ref BESecurityGroup
        #- Fn::ImportValue: IN-DefaultSecurityGroup
        AssociatePublicIpAddress: 'false'
        DeviceIndex: '0'
        DeleteOnTermination: 'true'
        SubnetId: !Ref BackEndVMSubnetId
        #  Fn::ImportValue: IN-PublicSubnet
  
Outputs:
  BackEndInstanceName:
    Value: !Ref BackEndInstance
    Description: Name of the Backend Instance
    Export:
      Name: !Sub "${AWS::StackName}-BackendInstance"